require 'bundler/setup'
Bundler.require
require_rel '../app'
require 'open-uri'
require 'nokogiri'
require 'colorize'
require 'pry'
require 'rainbow'
require 'text'
require 'launchy'
require 'artii'
require 'terminal-table'
require 'ffi'
require 'watir'
require 'io/console'
require 'curses'
# require 'terminfo'